# Generated by Django 5.1.1 on 2024-12-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0086_meeting_model_relocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('meeting_date', models.DateTimeField(verbose_name='Meeting Date')),
                ('sms', models.TextField(help_text='Note: SMS will prepend staff ID and append meeting date & venue', null=True)),
                ('sms_date', models.DateTimeField(verbose_name='SMS Date & Time')),
                ('location', models.CharField(max_length=100, verbose_name='Venue')),
                ('agenda', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on_going', 'On Going'), ('ended', 'Ended')], default='pending', max_length=10)),
                ('department', models.ManyToManyField(related_name='meetings', to='hr.department')),
                ('job', models.ManyToManyField(related_name='meetings', to='hr.job')),
                ('salary_grade', models.ManyToManyField(related_name='meetings', to='hr.salarygrade', verbose_name='Salary Grade')),
            ],
            options={
                'db_table': 'hr_meeting',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='administration.meeting')),
            ],
        ),
    ]
