# Generated by Django 5.1.1 on 2024-12-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_business_document_models_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, help_text='Provide detailed address, this may include digital address or post address', null=True, verbose_name='Address Info'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
