# Generated by Django 5.1.1 on 2024-12-09 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_vendor_email_required_contraint_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdocument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='businessdocument',
            name='document_file',
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='BusinessDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='business_documents/', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='administration.businessdocument')),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='administration.documentcategory', verbose_name='Document Category')),
            ],
        ),
    ]
