# Generated by Django 5.1.1 on 2024-12-09 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_business_document_models__modified_to_allow_multiple_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocumentfile',
            name='business_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='administration.businessdocument'),
        ),
        migrations.AlterField(
            model_name='businessdocumentfile',
            name='document_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='administration.documentcategory', verbose_name='Document Category'),
        ),
    ]
