# Generated by Django 5.1.1 on 2024-12-10 23:05

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_load_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocumentfile',
            name='document_file',
            field=models.FileField(upload_to=administration.models.file_upload_path, verbose_name='File'),
        ),
    ]
