# Generated by Django 5.1.1 on 2024-12-22 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('expense', 'Expense'), ('income', 'Income'), ('equity', 'Equity')], max_length=20, verbose_name='Account Type')),
                ('category_detail', models.CharField(choices=[('cash_equivalent', 'Cash Equivalent'), ('account_receivable', 'Account Receivable'), ('current_asset', 'Current Asset'), ('non_current_asset', 'Non-Current Asset'), ('fixed_asset', 'Fixed Asset'), ('current_liability', 'Current Liability'), ('account_payable', 'Account Payable'), ('non_current_liability', 'Non-Current Liability'), ('equity', 'Owners Equity'), ('income', 'Income'), ('other_income', 'Other Income'), ('expense', 'Expense'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('depreciation', 'Depreciation'), ('amortization', 'Amortization'), ('other_expense', 'Other Expense')], max_length=30, verbose_name='Account Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, unique=True, verbose_name='Account Name')),
                ('account_number', models.CharField(help_text='Not to be confused with bank a/c number', max_length=100, unique=True, verbose_name='Account Code/Number')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.accountcategory', verbose_name='Account Detail')),
            ],
        ),
    ]
