# Generated by Django 5.1.1 on 2024-12-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_load_asset_account_category'),
    ]
    def load_liability_account_categories(apps, schema_editor):
        AccountCategory = apps.get_model('finance', 'AccountCategory')
        categories = [
            # Liability class
            {'type': 'liability', 'category': 'current_liability'},
            {'type': 'liability', 'category': 'account_payable'},
            {'type': 'liability', 'category': 'non_current_liability'},
        ]
       
        for category in categories:
            AccountCategory.objects.create(category_type=category['type'], category_detail=category['category'])
        
    operations = [
        migrations.RunPython(load_liability_account_categories),
    ]
