# Generated by Django 5.1.1 on 2024-12-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_load_liability_account_category'),
    ]
    def load_equity_account_categories(apps, schema_editor):
        AccountCategory = apps.get_model('finance', 'AccountCategory')
        categories = [
            # Equity class
            {'type': 'equity', 'category': 'equity'},
            ]
        for category in categories:
            AccountCategory.objects.create(category_type=category['type'], category_detail=category['category'])
   
    operations = [
        migrations.RunPython(load_equity_account_categories),
    ]
