# Generated by Django 5.1.1 on 2024-12-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_load_equity_account_category'),
    ]
    def load_income_account_categories(apps, schema_editor):
        AccountCategory = apps.get_model('finance', 'AccountCategory')
        categories = [
            # Income class
            {'type': 'income', 'category': 'income'},
            {'type': 'income', 'category': 'other_income'},
        ]
        for category in categories:
            AccountCategory.objects.create(category_type=category['type'], category_detail=category['category'])
    operations = [
        migrations.RunPython(load_income_account_categories),
    ]
