# Generated by Django 5.1.1 on 2024-12-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_load_income_account_category'),
    ]
    def load_expense_account_categories(apps, schema_editor):
        AccountCategory = apps.get_model('finance', 'AccountCategory')
        categories = [
            # Expense class
            {'type': 'expense', 'category': 'expense'},
            {'type': 'expense', 'category': 'cost_of_goods_sold'},
            {'type': 'expense', 'category': 'operating_expense'},
            {'type': 'expense', 'category': 'depreciation'},
            {'type': 'expense', 'category': 'amortization'},
            {'type': 'expense', 'category': 'other_expense'},
        ]
        for category in categories:
            AccountCategory.objects.create(category_type=category['type'], category_detail=category['category'])
    operations = [
        migrations.RunPython(load_expense_account_categories),
    ]
