# Generated by Django 5.1.1 on 2024-12-23 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_load_expense_account_category'),
        ('hr', '0086_meeting_model_relocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='hr.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='finance.account', verbose_name='Parent Account'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_name'], name='finance_acc_account_aec444_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='finance_acc_account_932be5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_category'], name='finance_acc_account_3a50ee_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent_account'], name='finance_acc_parent__4795fd_idx'),
        ),
    ]
