# Generated by Django 5.1.1 on 2025-01-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    # load transaction categories 
    def load_transaction_categories(apps, schema_editor):
        transaction_categories = [
            {'type': 'Deposit', 'detail': 'Opening Balance', 'level': '1'},
            {'type': 'Transfer', 'detail': 'Deposit', 'level': '1'},
            {'type': 'Journal', 'detail': 'Opening Balance', 'level': '1'},
            {'type': 'Cash Payment', 'detail': 'expense', 'level': '1'},
            {'type': 'Bill', 'detail': 'expense', 'level': '1'},
            {'type': 'Journal Entry', 'detail': 'Journal', 'level': '1'},
            {'type': 'Transfer', 'detail': 'Contra', 'level': '1'},
            {'type': 'Bill Payment', 'detail': 'expense', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Bill Payment', 'level': '1'},
            {'type': 'Invoice', 'detail': 'receipt', 'level': '1'},
            {'type': 'Receive Payment', 'detail': 'receipt', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Receive Payment', 'level': '1'},
            {'type': 'Sales', 'detail': 'receipt', 'level': '1'},
            {'type': 'Withhold Payment', 'detail': 'expense', 'level': '1'},
            {'type': 'VAT Payment', 'detail': 'expense', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Withhold Payment', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'VAT Payment', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Bill', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Invoice', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Sales', 'level': '1'},
            {'type': 'Drawing', 'detail': 'cash withdrawals', 'level': '1'},
            {'type': 'Drawing', 'detail': 'asset withdrawals', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Cash Withdrawal', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Fixed Asset Withdrawal', 'level': '1'},
            {'type': 'Investment', 'detail': 'Cash Investment', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Cash Investment', 'level': '1'},
            {'type': 'Composite Payment', 'detail': 'expense', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Composite Payment', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'expense', 'level': '1'},
            {'type': 'Adjust Customer Balance', 'detail': 'expense', 'level': '1'},
            {'type': 'Refund', 'detail': 'expense', 'level': '3'},
            {'type': 'Adjusted Entry', 'detail': 'Refund', 'level': '1'},
            {'type': 'Adjust Customer Balance', 'detail': 'invoice', 'level': '1'},
            {'type': 'Interest Earn', 'detail': 'receipt', 'level': '1'},
            {'type': 'Adjust Customer Balance', 'detail': 'receipt', 'level': '1'},
            {'type': 'Transfer Refund', 'detail': 'expense', 'level': '1'},
            {'type': 'Discount Allowed', 'detail': 'expense', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Discount Allowed', 'level': '1'},
            {'type': 'Bank Charges', 'detail': 'expense', 'level': '1'},
            {'type': 'Advance', 'detail': 'Journal', 'level': '1'},
            {'type': 'Receive Advance', 'detail': 'Journal', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Advance', 'level': '1'},
            {'type': 'Expense Refund', 'detail': 'Journal', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Expense Refund', 'level': '1'},
            {'type': 'Adjusted Entry', 'detail': 'Receive Advance', 'level': '1'},
        ]
        
        TransactionCategory = apps.get_model('finance', 'TransactionCategory')
        
        for category in transaction_categories:
            TransactionCategory.objects.create(type=category['type'], detail=category['detail'], level=category['level'])
   
    dependencies = [
        ('finance', '0008_finance_transaction_models_created'),
    ]

    operations = [
        migrations.RunPython(load_transaction_categories),
    ]
