# Generated by Django 5.1.1 on 2025-01-04 16:41

from django.db import migrations


class Migration(migrations.Migration):
    def capitalize_transaction_category_detail(apps, schema_editor):
        TransactionCategory = apps.get_model('finance', 'TransactionCategory')
        for category in TransactionCategory.objects.all():
            category.detail = category.detail.title()
            category.save()

    dependencies = [
        ('finance', '0009_load_transaction_categories'),
    ]

    operations = [
        migrations.RunPython(
            capitalize_transaction_category_detail,
            migrations.RunPython.noop
        ),
    ]

