# Generated by Django 5.1.1 on 2024-10-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial_without_payroll_stuffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
