# Generated by Django 5.1.1 on 2024-10-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_salarygrade_added_jobtitle_remove'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salarygrade',
            unique_together={('grade', 'step')},
        ),
    ]
