# Generated by Django 5.1.1 on 2024-10-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_make_grade_step_as_unique_in_salarygrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=256, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(max_length=24, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.CharField(max_length=256, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Staff ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssnit',
            field=models.CharField(max_length=24, null=True, unique=True, verbose_name='SSNIT No.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(max_length=24, null=True, unique=True, verbose_name='TIN No.'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Hired Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='hr.salarygrade', verbose_name='Salary Grade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='hr.bank'),
        ),
    ]
