# Generated by Django 5.1.1 on 2024-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_load_bank_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euros'), ('GBP', 'British Pounds'), ('GHS', 'Ghanaian Cedi')], default='GHS', max_length=3),
        ),
    ]
