# Generated by Django 5.1.1 on 2024-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_add_currency_to_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euros'), ('GBP', 'British Pounds'), ('GHS', 'Ghanaian Cedi')], default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Salary'),
        ),
    ]
