# Generated by Django 5.1.1 on 2024-10-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employee_photo_path_enhance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Allow multiple documents of this type per employee?')),
            ],
        ),
        migrations.CreateModel(
            name='NationalIDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('block', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='ID Number'),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hr.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.documenttype'),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guarantor Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Guarantor Phone Number')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='hr.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.nationalidtype', verbose_name='National ID'),
        ),
    ]
