# Generated by Django 5.1.1 on 2024-10-14 12:27

from django.db import migrations

def load_document_types(apps, schema_editor):
    DocumentType = apps.get_model('hr', 'DocumentType')
    NationalIDType = apps.get_model('hr', 'NationalIDType')

    document_types = [
        {'name': 'Academic Certificate', 'allow_multiple': True},
        {'name': 'Professional Certificate', 'allow_multiple': True},
        {'name': 'Medical Certificate', 'allow_multiple': True},
        {'name': 'Employment Contract', 'allow_multiple': True},
        {'name': 'Non-Disclosure Agreement', 'allow_multiple': True},
        {'name': 'Curriculum Vitae', 'allow_multiple': False},
        {'name': 'Cover Letter', 'allow_multiple': False},
        {'name': 'License', 'allow_multiple': True},
        {'name': 'SSNIT', 'allow_multiple': False},
        {'name': 'Passport', 'allow_multiple': False},
        {'name': 'Ghana Card', 'allow_multiple': False},
        {'name': 'Work Permit/Visa', 'allow_multiple': True},
    ]

    id_types = [
        {'name': 'Ecowas/Ghana Card'},
        {'name': 'SSNIT Card'},
        {'name': 'NHIS Card'},
        {'name': 'Driver License'},
    ]

    # Load Document Types
    for doc_type in document_types:
        DocumentType.objects.get_or_create(
            name=doc_type['name'],
            defaults={'allow_multiple': doc_type['allow_multiple']}
        )
    
    # Load National ID Types
    for id_type in id_types:
        NationalIDType.objects.get_or_create(name=id_type['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_dates_column_updated'),
    ]

    operations = [
        migrations.RunPython(load_document_types),
    ]
