# Generated by Django 5.1.1 on 2024-10-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_load_document_types_and_national_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('id_type', 'id_number')},
        ),
    ]
