# Generated by Django 5.1.1 on 2024-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_unique_together_added_to_employee_id_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Guarantor Phone Number'),
        ),
        migrations.AlterUniqueTogether(
            name='guarantor',
            unique_together={('employee', 'name', 'phone_number')},
        ),
    ]
