# Generated by Django 5.1.1 on 2024-10-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_unique_together_added_to_guarantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(max_length=24, null=True, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
    ]
