# Generated by Django 5.1.1 on 2024-10-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_status_added_to_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guarantor',
            old_name='name',
            new_name='guarantor_name',
        ),
        migrations.RenameField(
            model_name='guarantor',
            old_name='phone_number',
            new_name='guarantor_phone_number',
        ),
        migrations.AlterUniqueTogether(
            name='guarantor',
            unique_together={('employee', 'guarantor_name', 'guarantor_phone_number')},
        ),
    ]
