# Generated by Django 5.1.1 on 2024-10-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    def load_leave_types(apps, shcema_editor):
        LeaveType = apps.get_model('hr', 'LeaveType')

        leave_types = [ 
            {"name": "Annual Leave", "entitlement": 20, "method": "accrual"},  # 20 days per year, accruing monthly
            {"name": "Sick Leave", "entitlement": 10, "method": "fixed"},  # 10 days per year, granted at the start of the year
            {"name": "Maternity Leave", "entitlement": 90, "method": "fixed"},  # 3 months for maternity leave, granted as needed
            {"name": "Paternity Leave", "entitlement": 10, "method": "fixed"},  # 10 days for fathers, granted at the birth of a child
            {"name": "Bereavement Leave", "entitlement": 5, "method": "fixed"},  # 5 days, granted when needed
            {"name": "Unpaid Leave", "entitlement": 0, "method": "fixed"},  # No entitlement, but granted as needed without pay
            {"name": "Compassionate Leave", "entitlement": 5, "method": "fixed"},  # 5 days for emergencies
            {"name": "Study/Exam Leave", "entitlement": 7, "method": "fixed"},  # 7 days per year for studies or exams
            {"name": "Public Holiday Leave", "entitlement": 10, "method": "fixed"},  # 10 public holidays (country-specific)
            {"name": "Jury Duty Leave", "entitlement": 10, "method": "fixed"},  # 10 days for jury duty
            {"name": "Casual Leave", "entitlement": 6, "method": "accrual"},  # 6 casual days per year, accruing bi-monthly
            {"name": "Adoption Leave", "entitlement": 60, "method": "fixed"},  # 2 months for adoption leave
            {"name": "Sabbatical Leave", "entitlement": 365, "method": "fixed"},  # 1 year after long service (granted as needed)
            {"name": "Emergency Leave", "entitlement": 7, "method": "fixed"},  # 7 days for urgent matters
            {"name": "Religious Leave", "entitlement": 3, "method": "fixed"},  # 3 days for religious observance
            {"name": "Special Leave", "entitlement": 10, "method": "fixed"},  # 10 days for miscellaneous needs
        ]
        for leave_type in leave_types:
            LeaveType.objects.create(
                name=leave_type['name'],
                entitlement=leave_type['entitlement'],
                method=leave_type['method']
            )

    dependencies = [
        ('hr', '0020_leave_submodule_models_created'),
    ]

    operations = [
        migrations.RunPython(load_leave_types)
    ]
