# Generated by Django 5.1.1 on 2024-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_add_field_allow_rollover_to_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
