# Generated by Django 5.1.1 on 2024-10-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    def load_holidays(apps, schemad_editor):
        PublicHoliday = apps.get_model('hr', 'PublicHoliday')
        public_holidays = [
            {"name": "New Year's Day", "date": "2024-01-01"},
            {"name": "Constitution Day", "date": "2024-01-07"},
            {"name": "Independence Day", "date": "2024-03-06"},
            {"name": "Good Friday", "date": "2024-03-29"},
            {"name": "Easter Monday", "date": "2024-04-01"},
            {"name": "May Day", "date": "2024-05-01"},
            {"name": "Africa Union Day", "date": "2024-05-25"},
            {"name": "Eid al-Fitr", "date": "2024-04-10"},  # Islamic date may vary
            {"name": "Eid al-Adha", "date": "2024-06-16"},  # Islamic date may vary
            {"name": "Republic Day", "date": "2024-07-01"},
            {"name": "Founders' Day", "date": "2024-08-04"},
            {"name": "Kwame Nkrumah Memorial Day", "date": "2024-09-21"},
            {"name": "Farmers' Day", "date": "2024-12-06"},
            {"name": "Christmas Day", "date": "2024-12-25"},
            {"name": "Boxing Day", "date": "2024-12-26"},
        ]  
        for public_holiday in public_holidays:
            PublicHoliday.objects.create(
                name=public_holiday['name'],
                date=public_holiday['date']
            )   
    dependencies = [
        ('hr', '0026_public_holiday_added_to_properly_calculate_leave_end_date'),
    ]

    operations = [
        migrations.RunPython(load_holidays)
    ]
