# Generated by Django 5.1.1 on 2024-10-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_unique_added_to_name_for_public_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical Skills'), ('project_management', 'Project Management & Leadership'), ('marketing', 'Marketing & Sales'), ('finance', 'Finance & Accounting'), ('hr', 'Human Resources'), ('design', 'Design & Creative'), ('customer_service', 'Customer Service & Support'), ('operations', 'Operations & Supply Chain'), ('legal', 'Legal & Compliance'), ('soft_skills', 'Soft Skills'), ('languages', 'Languages')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
