# Generated by Django 5.1.1 on 2024-10-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_load_skills_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='employees', to='hr.skill'),
        ),
    ]
