# Generated by Django 5.1.1 on 2024-11-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_meeting_and_attendance_models_greatly_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_going', 'On Going'), ('ended', 'Ended')], default='on_going', max_length=10),
        ),
    ]
