# Generated by Django 5.1.1 on 2024-11-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_status_added_to_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_going', 'On Going'), ('ended', 'Ended')], default='pending', max_length=10),
        ),
    ]
