# Generated by Django 5.1.1 on 2024-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0036_sms_model_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='job',
            field=models.ManyToManyField(related_name='sms', to='hr.job'),
        ),
    ]
