# Generated by Django 5.1.1 on 2024-11-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_job_added_to_sms_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name_plural': 'Sms'},
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractual', 'Contractual'), ('temporary', 'Temporary')], default='full_time', max_length=12),
        ),
    ]
