# Generated by Django 5.1.1 on 2024-11-07 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_employment_type_added_to_employee_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('alias_name', models.CharField(max_length=100, verbose_name='Alias Name')),
                ('effect', models.CharField(default='addition', max_length=10)),
                ('rate_type', models.CharField(default='fix', max_length=10, verbose_name='Rate Type')),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_dependency', models.CharField(max_length=120, null=True, verbose_name='Multiply By Rate (Enter text below)')),
                ('staff_source', models.CharField(default='filters', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1, verbose_name='Salary Step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='grade_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='steps', to='hr.salarystep'),
        ),
    ]
