# Generated by Django 5.1.1 on 2024-11-07 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_load_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarygrade',
            name='grade_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_grades', to='hr.salarystep'),
        ),
    ]
