# Generated by Django 5.1.1 on 2024-11-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0043_job_improved_with_accurate_skills_and_designation_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.designation'),
        ),
    ]
