# Generated by Django 5.1.1 on 2024-11-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    def load_designations(apps, schema_editor):
        Designation = apps.get_model('hr', 'Designation')
        designation_list = [
    # Education Sector
    {'code': 'EDU001', 'title': 'Professor', 'level': 'Senior'},
    {'code': 'EDU002', 'title': 'Associate Professor', 'level': 'Mid'},
    {'code': 'EDU003', 'title': 'Lecturer', 'level': 'Entry'},
    {'code': 'EDU004', 'title': 'Teaching Assistant', 'level': 'Entry'},
    {'code': 'EDU005', 'title': 'Dean of Faculty', 'level': 'Senior'},
    {'code': 'EDU006', 'title': 'Head of Department', 'level': 'Mid'},
    {'code': 'EDU007', 'title': 'Academic Advisor', 'level': 'Mid'},
    {'code': 'EDU008', 'title': 'Lab Technician', 'level': 'Entry'},

    # Finance Sector
    {'code': 'FIN001', 'title': 'Chief Financial Officer', 'level': 'Senior'},
    {'code': 'FIN002', 'title': 'Financial Analyst', 'level': 'Mid'},
    {'code': 'FIN003', 'title': 'Accountant', 'level': 'Entry'},
    {'code': 'FIN004', 'title': 'Auditor', 'level': 'Mid'},
    {'code': 'FIN005', 'title': 'Investment Manager', 'level': 'Senior'},
    {'code': 'FIN006', 'title': 'Risk Analyst', 'level': 'Mid'},
    {'code': 'FIN007', 'title': 'Treasury Analyst', 'level': 'Entry'},
    {'code': 'FIN008', 'title': 'Tax Consultant', 'level': 'Mid'},

    # Health Sector
    {'code': 'HEA001', 'title': 'Chief Medical Officer', 'level': 'Senior'},
    {'code': 'HEA002', 'title': 'Surgeon', 'level': 'Senior'},
    {'code': 'HEA003', 'title': 'General Practitioner', 'level': 'Mid'},
    {'code': 'HEA004', 'title': 'Nurse', 'level': 'Entry'},
    {'code': 'HEA005', 'title': 'Pharmacist', 'level': 'Mid'},
    {'code': 'HEA006', 'title': 'Medical Laboratory Scientist', 'level': 'Mid'},
    {'code': 'HEA007', 'title': 'Radiologist', 'level': 'Senior'},
    {'code': 'HEA008', 'title': 'Health Assistant', 'level': 'Entry'},

    # Government Sector
    {'code': 'GOV001', 'title': 'Minister', 'level': 'Senior'},
    {'code': 'GOV002', 'title': 'Deputy Minister', 'level': 'Senior'},
    {'code': 'GOV003', 'title': 'Permanent Secretary', 'level': 'Senior'},
    {'code': 'GOV004', 'title': 'Director', 'level': 'Mid'},
    {'code': 'GOV005', 'title': 'Assistant Director', 'level': 'Mid'},
    {'code': 'GOV006', 'title': 'Policy Analyst', 'level': 'Entry'},
    {'code': 'GOV007', 'title': 'Administrative Officer', 'level': 'Entry'},
    {'code': 'GOV008', 'title': 'Clerk', 'level': 'Entry'},

    # Technology Sector
    {'code': 'TEC001', 'title': 'Chief Technology Officer', 'level': 'Senior'},
    {'code': 'TEC002', 'title': 'Software Engineer', 'level': 'Mid'},
    {'code': 'TEC003', 'title': 'Data Scientist', 'level': 'Mid'},
    {'code': 'TEC004', 'title': 'System Administrator', 'level': 'Entry'},
    {'code': 'TEC005', 'title': 'IT Support Specialist', 'level': 'Entry'},
    {'code': 'TEC006', 'title': 'Cybersecurity Analyst', 'level': 'Mid'},
    {'code': 'TEC007', 'title': 'Database Administrator', 'level': 'Mid'},
    {'code': 'TEC008', 'title': 'Product Manager', 'level': 'Senior'},

    # Manufacturing Sector
    {'code': 'MAN001', 'title': 'Production Manager', 'level': 'Senior'},
    {'code': 'MAN002', 'title': 'Quality Assurance Specialist', 'level': 'Mid'},
    {'code': 'MAN003', 'title': 'Line Supervisor', 'level': 'Mid'},
    {'code': 'MAN004', 'title': 'Machine Operator', 'level': 'Entry'},
    {'code': 'MAN005', 'title': 'Assembly Technician', 'level': 'Entry'},
    {'code': 'MAN006', 'title': 'Safety Officer', 'level': 'Mid'},
    {'code': 'MAN007', 'title': 'Maintenance Engineer', 'level': 'Mid'},
    {'code': 'MAN008', 'title': 'Warehouse Manager', 'level': 'Senior'},

    # Retail Sector
    {'code': 'RET001', 'title': 'Store Manager', 'level': 'Senior'},
    {'code': 'RET002', 'title': 'Assistant Store Manager', 'level': 'Mid'},
    {'code': 'RET003', 'title': 'Sales Associate', 'level': 'Entry'},
    {'code': 'RET004', 'title': 'Cashier', 'level': 'Entry'},
    {'code': 'RET005', 'title': 'Inventory Specialist', 'level': 'Mid'},
    {'code': 'RET006', 'title': 'Customer Service Representative', 'level': 'Entry'},
    {'code': 'RET007', 'title': 'Merchandising Specialist', 'level': 'Mid'},
    {'code': 'RET008', 'title': 'Regional Manager', 'level': 'Senior'},

    # Logistics Sector
    {'code': 'LOG001', 'title': 'Logistics Manager', 'level': 'Senior'},
    {'code': 'LOG002', 'title': 'Supply Chain Analyst', 'level': 'Mid'},
    {'code': 'LOG003', 'title': 'Transportation Coordinator', 'level': 'Entry'},
    {'code': 'LOG004', 'title': 'Warehouse Clerk', 'level': 'Entry'},
    {'code': 'LOG005', 'title': 'Fleet Manager', 'level': 'Mid'},
    {'code': 'LOG006', 'title': 'Inventory Controller', 'level': 'Mid'},
    {'code': 'LOG007', 'title': 'Shipping Specialist', 'level': 'Entry'},
    {'code': 'LOG008', 'title': 'Procurement Officer', 'level': 'Senior'},
]


        Designation.objects.bulk_create([Designation(code=designation['code'], title=designation['title'], level=designation['level']) for designation in designation_list])
    dependencies = [
        ('hr', '0044_designation_added_to_employee'),
    ]

    operations = [
        migrations.RunPython(load_designations)
    ]
