# Generated by Django 5.1.1 on 2024-11-08 18:18

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_load_designations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
