# Generated by Django 5.1.1 on 2024-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0046_job_responsibilities_field_now_a_quilfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryitem',
            name='applicable_to',
            field=models.ManyToManyField(blank=True, related_name='applicable_salary_items', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='condition',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractual', 'Contractual'), ('temporary', 'Temporary')], default='full_time', max_length=12),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='department',
            field=models.ManyToManyField(related_name='salary_items', to='hr.department'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='designation',
            field=models.ManyToManyField(related_name='salary_items', to='hr.designation'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='excluded_from',
            field=models.ManyToManyField(blank=True, related_name='excluded_salary_items', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='expires_on',
            field=models.DateField(help_text='Leave blank if item will continually remain active', null=True, verbose_name='Expires On'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='job',
            field=models.ManyToManyField(related_name='salary_items', to='hr.job'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='salary_grade',
            field=models.ManyToManyField(related_name='salary_items', to='hr.salarygrade'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='step',
            field=models.ManyToManyField(related_name='salary_items', to='hr.salarystep'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='alias_name',
            field=models.CharField(help_text='Name will appear on payslip', max_length=100, verbose_name='Alias Name'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='effect',
            field=models.CharField(default='addition', max_length=10, verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='rate_dependency',
            field=models.CharField(help_text='Eg can be number of hours, marked scripts etc', max_length=120, null=True, verbose_name='Multiply By Rate'),
        ),
    ]
