# Generated by Django 5.1.1 on 2024-11-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0047_salary_item_improved_with_m2m_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='effect',
            field=models.CharField(choices=[('addition', 'Addition'), ('deduction', 'Deduction')], default='addition', max_length=10, verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='rate_type',
            field=models.CharField(choices=[('fix', 'Fix'), ('factor', 'Factor'), ('variable', 'Variable')], default='fix', max_length=10, verbose_name='Rate Type'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='staff_source',
            field=models.CharField(choices=[('filters', 'Filters'), ('import', 'Import')], default='filters', max_length=8),
        ),
    ]
