# Generated by Django 5.1.1 on 2024-11-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_choices_now_added_to_effect_rate_type_and_staff_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='rate_dependency',
            field=models.IntegerField(help_text='Eg can be number of hours, marked scripts etc', null=True, verbose_name='Multiply By Rate'),
        ),
    ]
