# Generated by Django 5.1.1 on 2024-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_rate_dependency_altered_from_char_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='applicable_to',
            field=models.ManyToManyField(blank=True, related_name='applicable_salary_items', to='hr.employee', verbose_name='Applicable To'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='excluded_from',
            field=models.ManyToManyField(blank=True, related_name='excluded_salary_items', to='hr.employee', verbose_name='Excluded From'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='salary_grade',
            field=models.ManyToManyField(related_name='salary_items', to='hr.salarygrade', verbose_name='Salary Grade'),
        ),
    ]
