# Generated by Django 5.1.1 on 2024-11-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0050_verbose_names_added_to_salaryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='rate_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate'),
        ),
    ]
