# Generated by Django 5.1.1 on 2024-11-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_verbose_names_added_to_rate_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='rate_dependency',
            field=models.CharField(help_text='Eg can be number of hours, marked scripts etc', max_length=100, null=True, verbose_name='Multiply By Rate'),
        ),
    ]
