# Generated by Django 5.1.1 on 2024-11-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_rate_dependency_changed_back_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='rate_dependency',
            field=models.CharField(help_text="Only use when rate is of type 'Variable'", max_length=100, null=True, verbose_name='Multiply By Rate'),
        ),
    ]
