# Generated by Django 5.1.1 on 2024-11-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0053_rate_dependency_helptext_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='salary_items', to='hr.department'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='designation',
            field=models.ManyToManyField(blank=True, related_name='salary_items', to='hr.designation'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='salary_items', to='hr.job'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='salary_grade',
            field=models.ManyToManyField(blank=True, related_name='salary_items', to='hr.salarygrade', verbose_name='Salary Grade'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='step',
            field=models.ManyToManyField(blank=True, related_name='salary_items', to='hr.salarystep'),
        ),
    ]
