# Generated by Django 5.1.1 on 2024-11-14 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_blank_added_to_salaryitem_m2m_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='item_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Item Name'),
        ),
        migrations.CreateModel(
            name='StaffSalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('salary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_salary_items', to='hr.salaryitem', verbose_name='Salary Item')),
            ],
            options={
                'unique_together': {('salary_item', 'employee')},
            },
        ),
    ]
