# Generated by Django 5.1.1 on 2024-11-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0055_staff_salary_item_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryitem',
            name='eligible_employee_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
