# Generated by Django 5.1.1 on 2024-11-15 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0056_eligible_employee_count_added_to_salaryitem_for_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='hr.designation'),
        ),
    ]
