# Generated by Django 5.1.1 on 2024-11-18 13:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_designation_linked_to_job_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('salary_advance', 'Salary Advance'), ('rent_advance', 'Rent Advance'), ('vehicle', 'Vehicle Loan'), ('personal', 'Personal Loan'), ('medical', 'Medical Loan'), ('education', 'Education Loan')], default='salary_advance', max_length=20, verbose_name='Loan Type')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interest Rate (%)')),
                ('duration_in_months', models.PositiveIntegerField(verbose_name='Duration (Months)')),
                ('monthly_installment', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monthly Installment')),
                ('total_repayable_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Repayable Amount')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Outstanding Balance')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted')], default='pending', max_length=10, verbose_name='Loan Status')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Loan Purpose')),
                ('applied_on', models.DateField(auto_now_add=True, verbose_name='Applied On')),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='Approved On')),
                ('deduction_end_date', models.DateField(blank=True, null=True, verbose_name='Deduction End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid')),
                ('date_paid', models.DateField(default=django.utils.timezone.now, verbose_name='Date Paid')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='hr.loan')),
            ],
        ),
    ]
