# Generated by Django 5.1.1 on 2024-11-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0059_loan_applied_on_made_for_manual_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='CreditUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_name', models.CharField(help_text='Union can be welfare group, bank etc', max_length=150, unique=True, verbose_name='Credit Union Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='If entered, will be the default for all staff in this union, leave it blank for varying amount', max_digits=12, null=True, verbose_name='Amount (Default)')),
                ('all_employee', models.BooleanField(default=False, verbose_name='Include All Staff')),
                ('deduction_start_date', models.DateField(blank=True, help_text='Default date where deduction will commmence for all employees', null=True, verbose_name='Deduction Start Date')),
                ('deduction_end_date', models.DateField(blank=True, help_text='When omitted, deduction will continue indefinitely.s', null=True, verbose_name='Deduction End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_to', models.ManyToManyField(blank=True, related_name='applicable_credit_unions', to='hr.employee', verbose_name='Applicable To')),
                ('department', models.ManyToManyField(blank=True, related_name='credit_unions', to='hr.department')),
                ('excluded_from', models.ManyToManyField(blank=True, related_name='excluded_credit_unions', to='hr.employee', verbose_name='Excluded From')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCreditUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Deduction')),
                ('deduction_start_date', models.DateField(help_text="Until date is entered, deduction won't take place", verbose_name='Deduction Start Date')),
                ('deduction_end_date', models.DateField(help_text='When omitted, deduction will continue indefinitely.', verbose_name='Deduction Start Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_unions', to='hr.creditunion', verbose_name='Credit Union')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_unions', to='hr.employee')),
            ],
        ),
    ]
