# Generated by Django 5.1.1 on 2024-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0060_credit_union_models_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
