# Generated by Django 5.1.1 on 2024-11-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0061_created_and_updated_dates_in_loanrepayment_omitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditunion',
            name='deduction_end_date',
            field=models.DateField(blank=True, help_text='When omitted, deduction will continue indefinitely', null=True, verbose_name='Deduction End Date'),
        ),
    ]
