# Generated by Django 5.1.1 on 2024-11-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0062_created_and_updated_dates_in_loanrepayment_omitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcreditunion',
            name='deduction_end_date',
            field=models.DateField(blank=True, help_text='When omitted, deduction will continue indefinitely.', null=True, verbose_name='Deduction Start Date'),
        ),
        migrations.AlterField(
            model_name='staffcreditunion',
            name='deduction_start_date',
            field=models.DateField(blank=True, help_text="Until date is entered, deduction won't take place", null=True, verbose_name='Deduction Start Date'),
        ),
    ]
