# Generated by Django 5.1.1 on 2024-11-23 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0063_null_added_to_deduction_start_and_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_month', models.PositiveIntegerField(verbose_name='Processing Month')),
                ('process_year', models.PositiveIntegerField(verbose_name='Processing Year')),
                ('description', models.CharField(max_length=255, blank=True, null=True, verbose_name='Payroll Description')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('posted', models.BooleanField(default=False, verbose_name='Is Posted')),
                ('condition', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractual', 'Contractual'), ('temporary', 'Temporary')], default='full_time', max_length=12, verbose_name='Employment Type')),
                ('payment_rate', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Payment Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_to', models.ManyToManyField(blank=True, related_name='applicable_payrolls', to='hr.employee', verbose_name='Applicable To')),
                ('departments', models.ManyToManyField(blank=True, related_name='payrolls', to='hr.department', verbose_name='Departments')),
                ('designations', models.ManyToManyField(blank=True, related_name='payrolls', to='hr.designation', verbose_name='Designations')),
                ('excluded_from', models.ManyToManyField(blank=True, related_name='excluded_payrolls', to='hr.employee', verbose_name='Excluded From')),
                ('salary_grades', models.ManyToManyField(blank=True, related_name='payrolls', to='hr.salarygrade', verbose_name='Salary Grades')),
            ],
            options={
                'verbose_name_plural': 'Payrolls',
                'unique_together': {('process_month', 'process_year', 'payment_rate', 'description', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('salary_item', 'Salary Item'), ('loan', 'Loan'), ('credit_union', 'Credit Union'), ('tax', 'Tax'), ('tax_relief', 'Tax Relief'), ('employer_ssnit', 'Employer SSNIT'), ('employee_ssnit', 'Employee SSNIT'), ('bank', 'Bank'), ('gross_salary', 'Gross Salary'), ('basic_salary', 'Basic Salary'), ('net_salary', 'Net Salary'), ('step', 'Step'), ('other', 'Other')], max_length=20, verbose_name='Item Type')),
                ('dependency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dependency ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('entry', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='hr.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.payroll')),
            ],
            options={
                'verbose_name_plural': 'Payroll Items',
            },
        ),
    ]
