# Generated by Django 5.1.1 on 2024-11-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0064_payroll_models_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='step',
            field=models.ManyToManyField(blank=True, related_name='payroll', to='hr.salarystep'),
        ),
    ]
