# Generated by Django 5.1.1 on 2024-11-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0065_step_filter_added_to_payroll_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='condition',
            field=models.CharField(choices=[('all', 'All Types'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractual', 'Contractual'), ('temporary', 'Temporary')], default='all', max_length=12, verbose_name='Employment Type'),
        ),
    ]
