# Generated by Django 5.1.1 on 2024-11-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0066_all_added_to_employment_type_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='departments',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='designations',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='salary_grades',
            new_name='salary_grade',
        ),
    ]
