# Generated by Django 5.1.1 on 2024-11-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0068_verbose_name_added_to_step_in_payroll_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='entry',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6, null=True),
        ),
    ]
