# Generated by Django 5.1.1 on 2024-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0070_tax_relief_added_to_employee_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='active_on',
            field=models.DateField(blank=True, null=True, verbose_name='Active On'),
        ),
    ]
