# Generated by Django 5.1.1 on 2024-11-24 23:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0071_active_on_added_to_loan_to_track_date_pv_was_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCreditUnionDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateField(default=django.utils.timezone.now, verbose_name='Date Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_credit_union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_unions', to='hr.staffcreditunion', verbose_name='Staff Credit Union')),
            ],
        ),
    ]
