# Generated by Django 5.1.1 on 2024-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0072_staff_credit_union_deduction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='error_mode',
            field=models.CharField(choices=[('strict', 'Strict mode ensures all staff records are accurate and complete before processing'), ('mute', 'Mute/Silence mode processes payroll to the exclusion of staff with incomplete records')], default='strict', max_length=12, verbose_name='Error Processing Mode'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='process_month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=12, verbose_name='Processing Month'),
        ),
    ]
