# Generated by Django 5.1.1 on 2024-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0074_payroll_error_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollerror',
            name='error_category',
            field=models.CharField(choices=[('bank', 'Missing Bank Details'), ('salary_grade', 'Missing Salary Grade'), ('double_entry', 'Double Entry Failure')], max_length=12),
        ),
    ]
