# Generated by Django 5.1.1 on 2024-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0077_taxability_added_to_payrollitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollitem',
            name='item_type',
            field=models.CharField(choices=[('salary_item', 'Salary Item'), ('loan', 'Loan'), ('credit_union', 'Credit Union'), ('tax', 'Tax'), ('tax_relief', 'Tax Relief'), ('employer_ssnit', 'Employer SSNIT'), ('employee_ssnit', 'Employee SSNIT'), ('bank', 'Bank'), ('gross_salary', 'Gross Salary'), ('basic_salary', 'Basic Salary'), ('net_salary', 'Net Salary'), ('step', 'Step'), ('salary_grade', 'Salary Grade'), ('taxable', 'Taxable'), ('other', 'Other')], max_length=20, verbose_name='Item Type'),
        ),
    ]
