# Generated by Django 5.1.1 on 2024-11-27 20:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0078_taxability_changed_to_taxable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Outstanding Balance'),
        ),
    ]
