# Generated by Django 5.1.1 on 2024-11-30 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0080_earning_and_deduction_added_to_payrollitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='hr.bank'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='credit_union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='hr.creditunion'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='hr.loan'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='salary_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='hr.salaryitem'),
        ),
    ]
