# Generated by Django 5.1.1 on 2024-11-30 04:03

from django.db import migrations, transaction

class Migration(migrations.Migration):

    def update_payrollitem_objects(app, shema_object):
        PayrollItem = app.get_model('hr', 'PayrollItem')
        Bank = app.get_model('hr', 'Bank')
        Loan = app.get_model('hr', 'Loan')
        SalaryItem = app.get_model('hr', 'SalaryItem')
        CreditUnion = app.get_model('hr', 'CreditUnion')

        # create look ups dictionaries
        bank_lookup = {str(bank.id) : bank for bank in Bank.objects.all()}
        loan_lookup = {str(loan.id) : loan for loan in Loan.objects.all()}
        salary_item_lookup = {str(salary_item.id) : salary_item for salary_item in SalaryItem.objects.all()}
        credit_union_lookup = {str(credit_union.id) : credit_union for credit_union in CreditUnion.objects.all()}

        bulk_update_entries = []
        
        with transaction.atomic():
            for item in PayrollItem.objects.all():
                item_type = item.item_type
                dependency_id = str(item.dependency)
                if item_type == 'bank' and not item.bank and dependency_id in bank_lookup:
                    item.bank=bank_lookup[dependency_id]
                if item_type == 'loan' and not item.loan and dependency_id in loan_lookup:
                    item.loan=loan_lookup[dependency_id]
                if item_type == 'salary_item' and not item.salary_item and dependency_id in salary_item_lookup:
                    item.salary_item=salary_item_lookup[dependency_id]
                if item_type == 'credit_union' and not item.credit_union and dependency_id in credit_union_lookup:
                    item.credit_union=credit_union_lookup[dependency_id]

                if item.bank or item.loan or item.credit_union or item.salary_item:
                    bulk_update_entries.append(item)

            # Perform bulk update
            if bulk_update_entries:
                PayrollItem.objects.bulk_update(
                    bulk_update_entries, 
                    ['bank', 'loan', 'credit_union', 'salary_item']
                )


    dependencies = [
        ('hr', '0081_dependency_actual_foreign_keys_added_for_flexible_querying'),
    ]

    operations = [
        migrations.RunPython(update_payrollitem_objects)
    ]
