# Generated by Django 5.1.1 on 2024-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0082_update_payrollitem_foreign_keys'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name', 'last_name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone_number'], name='phone_number_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_type', 'status'], name='loantype_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_type'], name='loan_type_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['employee', 'status'], name='loan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['active_on'], name='active_on_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['deduction_end_date'], name='loan_end_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['process_month', 'process_year'], name='month_year_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['active'], name='active_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['posted'], name='posted_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollerror',
            index=models.Index(fields=['payroll', 'error_category'], name='payroll_errorcategory_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollerror',
            index=models.Index(fields=['error_category'], name='error_cateogry_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['payroll', 'item_type'], name='payroll_itemtype_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['item_type'], name='item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['amount'], name='amount_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['entry'], name='entry_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['dependency'], name='dependency_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcreditunion',
            index=models.Index(fields=['deduction_start_date'], name='cu_deduction_start_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcreditunion',
            index=models.Index(fields=['deduction_end_date'], name='cu_deduction_end_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcreditunion',
            index=models.Index(fields=['employee'], name='cu_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcreditunion',
            index=models.Index(fields=['credit_union'], name='cu_union_idx'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['year'], name='tax_year_idx'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['rate'], name='tax_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['block'], name='tax_block_idx'),
        ),
    ]
