# Generated by Django 5.1.1 on 2024-12-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0084_payrollitem_index_enhanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='pv_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of Vouchers'),
        ),
    ]
