# Generated by Django 5.1.1 on 2024-12-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0085_pv_counted_added_to_payroll_to_track_number_of_pv_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='department',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='job',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='salary_grade',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
