# Generated by Django 5.1.1 on 2025-01-13 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0086_meeting_model_relocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarygrade',
            name='step',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
