# Generated by Django 5.1.1 on 2024-12-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_store_pos_sale_and_other_models_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
    ]
