# Generated by Django 5.1.1 on 2024-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0086_meeting_model_relocated'),
        ('operations', '0004_indexes_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('ltr', 'Liter'), ('oz', 'Ounce'), ('lb', 'Pound')], default='kg', max_length=3, verbose_name='Weight Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='operations__company_ac6873_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['contact_person'], name='operations__contact_3d540f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse'], name='operations__warehou_04c8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product'], name='operations__product_632b14_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorydamage',
            index=models.Index(fields=['inventory'], name='operations__invento_cad3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorydamage',
            index=models.Index(fields=['date_reported'], name='operations__date_re_cc4978_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='operations__product_66a34b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_category'], name='operations__product_4ca125_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['weight', 'weight_unit'], name='operations__weight_8ca488_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['category_name'], name='operations__categor_e95c42_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='operations__po_numb_a4569a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='operations__supplie_dac563_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='operations__status_1ac0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderdetail',
            index=models.Index(fields=['purchase_order'], name='operations__purchas_a83c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderdetail',
            index=models.Index(fields=['product'], name='operations__product_ea87cc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company_name'], name='operations__company_36bf46_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['contact_person'], name='operations__contact_7e6dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['source'], name='operations__source__779ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['destination'], name='operations__destina_fa53eb_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['product'], name='operations__product_628df3_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='operations__status_6633ca_idx'),
        ),
        migrations.AddIndex(
            model_name='van',
            index=models.Index(fields=['plate_number'], name='operations__plate_n_ee8fef_idx'),
        ),
        migrations.AddIndex(
            model_name='van',
            index=models.Index(fields=['vin'], name='operations__vin_699e77_idx'),
        ),
        migrations.AddIndex(
            model_name='van',
            index=models.Index(fields=['status'], name='operations__status_e7e5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='van',
            index=models.Index(fields=['assigned_driver'], name='operations__assigne_72dcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_name'], name='operations__warehou_8c99ea_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['manager'], name='operations__manager_75d506_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['status'], name='operations__status_d832f7_idx'),
        ),
    ]
