# Generated by Django 5.1.1 on 2024-12-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0086_meeting_model_relocated'),
        ('operations', '0005_weight_unit_added_to_product_and_indexes_to_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Route Name')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distance (km)')),
                ('estimated_time', models.DurationField(verbose_name='Estimated Travel Time')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_ends', to='operations.warehouse')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_starts', to='operations.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
                ('estimated_arrival', models.DateTimeField(verbose_name='Estimated Arrival')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_schedules', to='hr.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='operations.deliveryroute')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_schedules', to='operations.van')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
    ]
