# Generated by Django 5.1.1 on 2025-01-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_logistics_models_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryroute',
            name='end_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_ends', to='operations.warehouse', verbose_name='End Point'),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='start_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_starts', to='operations.warehouse', verbose_name='Start Point'),
        ),
    ]
