# Generated by Django 5.1.1 on 2024-12-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0086_meeting_model_relocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleManTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Target')),
                ('weekly_target', models.DecimalField(decimal_places=2, help_text='Becomes necessary as some sales men may work for entire 7 days while certain days may be omitted for some', max_digits=10, verbose_name='Weekly Target')),
                ('monthly_target', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Monthly Target')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_targets', to='hr.employee', verbose_name='Sales Man')),
            ],
            options={
                'verbose_name_plural': 'Sales Man Targets',
            },
        ),
    ]
