# Generated by Django 5.1.1 on 2024-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0086_meeting_model_relocated'),
        ('operations', '0004_indexes_added'),
        ('sales', '0002_store_pos_sale_and_other_models_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledamage',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='pos',
            index=models.Index(fields=['pos_number'], name='sales_pos_pos_num_5556e5_idx'),
        ),
        migrations.AddIndex(
            model_name='pos',
            index=models.Index(fields=['store'], name='sales_pos_store_i_a51aff_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='sales_sale_sale_nu_99d8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['pos'], name='sales_sale_pos_id_e57244_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='sales_sale_custome_f0dcab_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['salesman'], name='sales_sale_salesma_29f9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_sale_da_2fd927_idx'),
        ),
        migrations.AddIndex(
            model_name='saledamage',
            index=models.Index(fields=['sale'], name='sales_saled_sale_id_7e22dc_idx'),
        ),
        migrations.AddIndex(
            model_name='saledamage',
            index=models.Index(fields=['product'], name='sales_saled_product_2718e5_idx'),
        ),
        migrations.AddIndex(
            model_name='saledamage',
            index=models.Index(fields=['date_reported'], name='sales_saled_date_re_c41b37_idx'),
        ),
        migrations.AddIndex(
            model_name='saledetail',
            index=models.Index(fields=['sale'], name='sales_saled_sale_id_b1965c_idx'),
        ),
        migrations.AddIndex(
            model_name='saledetail',
            index=models.Index(fields=['product'], name='sales_saled_product_9cdcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='salemantarget',
            index=models.Index(fields=['sales_man'], name='sales_salem_sales_m_977d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_name'], name='sales_store_store_n_dfb397_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['warehouse'], name='sales_store_warehou_49e1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['manager'], name='sales_store_manager_456f64_idx'),
        ),
    ]
