# Generated by Django 5.1.1 on 2025-01-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_logistics_models_added'),
        ('sales', '0003_indexes_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('partial', 'Partially Delivered'), ('failed', 'Failed')], max_length=20)),
                ('delivery_note_number', models.CharField(max_length=50, unique=True)),
                ('delivery_address', models.TextField()),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.deliveryschedule')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_deliver', models.PositiveIntegerField()),
                ('quantity_delivered', models.PositiveIntegerField(default=0)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('damaged', 'Damaged in Transit')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.delivery')),
                ('sale_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saledetail')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery'], name='sales_deliv_deliver_a2d2be_idx'), models.Index(fields=['sale_detail'], name='sales_deliv_sale_de_11ce86_idx'), models.Index(fields=['status'], name='sales_deliv_status_0e60c2_idx')],
            },
        ),
    ]
