# Generated by Django 5.1.1 on 2025-01-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_logistic_extended_with_delivery_models_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_note_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Delivery Note Number'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('partial', 'Partially Delivered'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recipient_name',
            field=models.CharField(max_length=100, verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recipient_phone',
            field=models.CharField(max_length=20, verbose_name='Recipient Phone'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity_delivered',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Delivered'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Returned'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity_to_deliver',
            field=models.PositiveIntegerField(verbose_name='Quantity to Deliver'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saledetail', verbose_name='Sale Item'),
        ),
    ]
